In [1]:
from pycba.sample_projects import load_sample_bypass

byp = load_sample_bypass()

In [2]:
byp["RP"]

,name,variant_0,variant_1,length,length_bridges,length_tunnels,category,lanes,environment,width,layout,toll_sections
id_section,,,,,,,,,,,,
0,entrance,1,1,0.5,0.0,0,standard,2,extravilan,9.5,wide,1
1,city,1,1,4.0,0.0,0,standard,2,intravilan,9.5,narrow,1
2,exit,1,1,0.4,0.0,0,standard,2,extravilan,9.5,wide,1
3,bypass,0,1,3.9,0.1,0,standard,2,extravilan,11.5,wide,1

In [3]:
byp["C_fin"]

                                      2020      2021      2022
item                category
planning and design preparation     150000    150000    150000
land                preparation     300000    300000    300000
site preparation    construction         0         0         0
earthworks          construction         0         0         0
pavements asphalt   construction  14000000  14000000  14000000
pavements concrete  construction         0         0         0
bridges             construction   1500000   1500000   1500000
tunnels             construction         0         0         0
buildings           construction         0         0         0
slope stabilisation construction         0         0         0
retaining walls     construction         0         0         0
noise barriers      construction    300000    300000    300000
safety features     construction         0         0         0
technology          construction         0         0         0
induced investment  construction         0         0         0
other               construction         0         0         0
supervision         other            20000     20000     20000
other services      other                0         0         0
contingencies       other                0         0         0
price adjustments   other                0         0         0

Capital expenditures (CAPEX) is a dataframe of investment in every of the building years.
The investment items fall into several categories.

In [4]:
byp["I0"]

                     2020   2021   2022   2023   2024   2025   2026   2027  \
id_section vehicle
0          bus         20     20     20     20     20     20     20     20
           car       9000   9090   9181   9273   9366   9460   9555   9651
           hgv       1000   1010   1020   1030   1040   1050   1061   1072
           lgv          0      0      0      0      0      0      0      0
1          bus         20     20     20     20     20     20     20     20
           car      10000  10100  10201  10303  10406  10510  10615  10721
           hgv       1000   1010   1020   1030   1040   1050   1061   1072
           lgv          0      0      0      0      0      0      0      0
2          bus         20     20     20     20     20     20     20     20
           car       8000   8080   8161   8243   8325   8408   8492   8577
           hgv       1000   1010   1020   1030   1040   1050   1061   1072
           lgv          0      0      0      0      0      0      0      0

                     2028   2029  ...   2040   2041   2042   2043   2044  \
id_section vehicle                ...
0          bus         20     20  ...     20     20     20     20     20
           car       9748   9845  ...  10982  11092  11203  11315  11428
           hgv       1083   1094  ...   1220   1232   1244   1256   1269
           lgv          0      0  ...      0      0      0      0      0
1          bus         20     20  ...     20     20     20     20     20
           car      10828  10936  ...  12201  12323  12446  12570  12696
           hgv       1083   1094  ...   1220   1232   1244   1256   1269
           lgv          0      0  ...      0      0      0      0      0
2          bus         20     20  ...     20     20     20     20     20
           car       8663   8750  ...   9763   9861   9960  10060  10161
           hgv       1083   1094  ...   1220   1232   1244   1256   1269
           lgv          0      0  ...      0      0      0      0      0

                     2045   2046   2047   2048   2049
id_section vehicle
0          bus         20     20     20     20     20
           car      11542  11657  11774  11892  12011
           hgv       1282   1295   1308   1321   1334
           lgv          0      0      0      0      0
1          bus         20     20     20     20     20
           car      12823  12951  13081  13212  13344
           hgv       1282   1295   1308   1321   1334
           lgv          0      0      0      0      0
2          bus         20     20     20     20     20
           car      10263  10366  10470  10575  10681
           hgv       1282   1295   1308   1321   1334
           lgv          0      0      0      0      0

[12 rows x 30 columns]

In [5]:
byp["V0"]

                    2020  2021  2022  2023  2024  2025  2026  2027  2028  \
id_section vehicle
0          bus        70    70    70    75    75    75    75    75    75
           car        80    80    80    80    80    80    80    80    80
           hgv        70    70    70    70    70    70    70    70    70
           lgv        80    80    80    80    80    80    80    80    80
1          bus        50    50    50    50    50    50    50    50    50
           car        50    50    50    50    50    50    50    50    50
           hgv        50    50    50    50    50    50    50    50    50
           lgv        50    50    50    50    50    50    50    50    50
2          bus        70    70    70    75    75    75    75    75    75
           car        80    80    80    80    80    80    80    80    80
           hgv        70    70    70    70    70    70    70    70    70
           lgv        80    80    80    80    80    80    80    80    80

                    2029  ...  2040  2041  2042  2043  2044  2045  2046  2047  \
id_section vehicle        ...
0          bus        75  ...    75    75    75    75    75    75    75    75
           car        80  ...    80    80    80    80    80    80    80    80
           hgv        70  ...    70    70    70    70    70    70    70    70
           lgv        80  ...    80    80    80    80    80    80    80    80
1          bus        50  ...    50    50    50    50    50    50    50    50
           car        50  ...    50    50    50    50    50    50    50    50
           hgv        50  ...    50    50    50    50    50    50    50    50
           lgv        50  ...    50    50    50    50    50    50    50    50
2          bus        75  ...    75    75    75    75    75    75    75    75
           car        80  ...    80    80    80    80    80    80    80    80
           hgv        70  ...    70    70    70    70    70    70    70    70
           lgv        80  ...    80    80    80    80    80    80    80    80

                    2048  2049
id_section vehicle
0          bus        75    75
           car        80    80
           hgv        70    70
           lgv        80    80
1          bus        50    50
           car        50    50
           hgv        50    50
           lgv        50    50
2          bus        75    75
           car        80    80
           hgv        70    70
           lgv        80    80

[12 rows x 30 columns]

In [6]:
from pycba import RoadCBA

yr_start = 2020
price_level = 2020
country = "svk"

rcba = RoadCBA(yr_start, price_level, country)
rcba.load_parameters(source="default")
rcba.read_project_inputs(byp["RP"], byp["C_fin"], byp["I0"], byp["I1"], byp["V0"], byp["V1"])

In [7]:
rcba.economic_analysis()

/Users/ayaanhaque/Desktop/Traffix/notebooks/cost-prediction/pycba/param_container.py:222: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  vtts = vtts.groupby(["vehicle"])["gdp_ga2", "value2"].sum()

Done. Time: 1.56 s.

In [8]:
rcba.df_enpv

                       value
type    item
cost    capex   -41953269.84
        opex     -2077088.92
benefit res_val   1689630.93
        vtts     21125949.30
        voc       9083415.88
        acc       3237916.19
        fuel      2360650.55
        ghg        588108.37
        em        3599053.73
        noise     5681462.45

In [9]:
rcba.df_eco

                       2020        2021        2022        2023        2024  \
type    item
cost    capex   -14672000.0 -14672000.0 -14672000.0       -0.00       -0.00
        opex           -0.0        -0.0        -0.0   -87935.90   -87935.90
benefit res_val         0.0         0.0         0.0        0.00        0.00
        vtts            0.0         0.0         0.0  1444438.47  1458422.49
        voc             0.0         0.0         0.0   610608.50   616696.70
        acc             0.0         0.0         0.0   221804.96   223865.98
        fuel            0.0         0.0         0.0   159101.27   160688.78
        ghg             0.0         0.0         0.0    32658.63    33852.48
        em              0.0         0.0         0.0   256850.05   259409.99
        noise           0.0         0.0         0.0   388864.61   392491.38

                       2025        2026        2027        2028        2029  \
type    item
cost    capex         -0.00       -0.00       -0.00       -0.00       -0.00
        opex      -87935.90   -87935.90   -87935.90   -87935.90   -87935.90
benefit res_val        0.00        0.00        0.00        0.00        0.00
        vtts     1470232.58  1485354.36  1499453.25  1514782.51  1529016.17
        voc       622598.75   630565.97   638368.94   646418.29   654248.63
        acc       225690.04   227909.12   230055.21   232316.82   234482.24
        fuel      162232.92   164194.77   166118.17   168103.58   170038.23
        ghg        35054.44    36368.31    37695.11    39056.75    40428.34
        em        261949.15   265132.40   268297.23   271500.03   274678.51
        noise     395812.38   399725.03   403569.98   407500.72   411439.79

                 ...        2040        2041        2042        2043  \
type    item     ...
cost    capex    ...       -0.00       -0.00       -0.00       -0.00
        opex     ...   -87935.90   -87935.90   -87935.90   -87935.90
benefit res_val  ...        0.00        0.00        0.00        0.00
        vtts     ...  1689470.13  1706276.72  1723261.45  1739902.67
        voc      ...   736454.66   743802.11   751182.41   758584.61
        acc      ...   258636.04   261225.61   263842.87   266283.67
        fuel     ...   190991.40   192899.86   194820.81   196746.69
        ghg      ...    51616.03    52653.05    53703.70    54766.06
        em       ...   246679.39   249156.80   251646.26   254137.39
        noise    ...   453890.46   458480.29   463098.78   467433.45

                       2044        2045        2046        2047        2048  \
type    item
cost    capex         -0.00       -0.00       -0.00       -0.00       -0.00
        opex      -87935.90   -87935.90  -929375.72   -87935.90   -87935.90
benefit res_val        0.00        0.00        0.00        0.00        0.00
        vtts     1757084.06  1774438.07  1791841.73  1809423.51  1825759.36
        voc       766019.66   773482.09   780993.79   788538.34   796137.63
        acc       268935.95   271613.61   274311.88   277037.83   279605.57
        fuel      198685.04   200634.64   202595.33   204568.49   206559.06
        ghg        55842.21    56931.92    58035.22    59152.60    60285.54
        em        256640.57   259155.39   261673.97   264204.59   266748.94
        noise     472077.80   476750.79   481423.83   486125.51   490541.00

                       2049
type    item
cost    capex         -0.00
        opex      -87935.90
benefit res_val  6954750.00
        vtts     1843028.27
        voc       802284.97
        acc       282277.20
        fuel      208272.40
        ghg        61344.33
        em        269007.31
        noise     495266.38

[10 rows x 30 columns]

In [10]:
del rcba
rcba = RoadCBA(yr_start, price_level, "svk", verbose=True)

In [11]:
rcba.load_parameters()
rcba.read_project_inputs(byp["RP"], byp["C_fin"], byp["I0"], byp["I1"], byp["V0"], byp["V1"])

# for reading whole excel files use this with the name of the Excel sheet:
# rcba.read_project_inputs_xls()

Reading CBA parameters...
Reading project inputs from df...

In [12]:
# content of the `df_raw` dictionary
rcba.df_raw.keys()

dict_keys(['c_op', 'toll_op', 'res_val', 'c_fuel', 'conv_fac', 'occ_p', 'occ_f', 'r_tp', 'vtts', 'voc', 'fuel_coeffs', 'r_fuel', 'r_acc', 'c_acc', 'r_ghg', 'c_ghg', 'r_em', 'c_em', 'noise'])

In [13]:
rcba.prepare_parameters()

Adjusting CPI...
Cleaning parameters...
    Cleaning: c_op
    Cleaning: toll_op
    Cleaning: res_val
    Cleaning: c_fuel
    Cleaning: conv_fac
    Cleaning: occ_p
    Cleaning: occ_f
    Cleaning: r_tp
    Cleaning: vtts
    Cleaning: voc
    Cleaning: fuel_coeffs
    Cleaning: r_fuel
    Cleaning: r_acc
    Cleaning: c_acc
    Cleaning: r_ghg
    Cleaning: c_ghg
    Cleaning: r_em
    Cleaning: c_em
    Cleaning: noise
Changing scale of c_ghg
Changing scale of c_em
Changing scale of noise
Adjusting price level...
    Adjusting: c_op
    Adjusting: toll_op
    Adjusting: vtts
    Adjusting: voc
    Adjusting: c_fuel
    Adjusting: c_acc
    Adjusting: c_ghg
    Adjusting: c_em
    Adjusting: noise
Wrangling parameters...
Averaging VTTS over distance type.

/Users/ayaanhaque/Desktop/Traffix/notebooks/cost-prediction/pycba/param_container.py:222: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  vtts = vtts.groupby(["vehicle"])["gdp_ga2", "value2"].sum()

In [14]:
rcba.compute_capex()
rcba.C_fin

Computing CAPEX...

,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,...,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049
item,,,,,,,,,,,,,,,,,,,,,
planning and design,150000,150000,150000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
land,300000,300000,300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
site preparation,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
earthworks,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pavements asphalt,14000000,14000000,14000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pavements concrete,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
bridges,1500000,1500000,1500000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tunnels,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
buildings,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
slope stabilisation,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
retaining walls,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
noise barriers,300000,300000,300000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
safety features,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
technology,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
induced investment,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
other,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
supervision,20000,20000,20000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
other services,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
contingencies,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
price adjustments,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
rcba._create_unit_cost_matrix()
rcba._create_unit_cost_opex_mask()

Creating time matrices for benefits...
    Creating: c_op
    Creating: toll_op
    Creating: vtts
    Creating: voc
    Creating: c_fuel
    Creating: c_acc
    Creating: c_em
    Creating: noise

In [16]:
rcba.UC.keys()

dict_keys(['c_op', 'toll_op', 'vtts', 'voc', 'c_fuel', 'c_acc', 'c_em', 'noise', 'c_ghg'])

In [17]:
rcba.compute_opex()
rcba.O0_eco

Computing OPEX...

                                                   2020        2021  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2022        2023  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2024        2025  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2026        2027  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2028        2029  ...  \
id_section operation_type item                                       ...
0          periodic       bridges                0.0000      0.0000  ...
                          pavements renewal      0.0000      0.0000  ...
                          pavements repair       0.0000      0.0000  ...
                          road marking           0.0000      0.0000  ...
                          tunnels                0.0000      0.0000  ...
           routine        bridges                0.0000      0.0000  ...
                          pavements           9080.3375   9080.3375  ...
                          tunnels                0.0000      0.0000  ...
1          periodic       bridges                0.0000      0.0000  ...
                          pavements renewal      0.0000      0.0000  ...
                          pavements repair       0.0000      0.0000  ...
                          road marking           0.0000      0.0000  ...
                          tunnels                0.0000      0.0000  ...
           routine        bridges                0.0000      0.0000  ...
                          pavements          72642.7000  72642.7000  ...
                          tunnels                0.0000      0.0000  ...
2          periodic       bridges                0.0000      0.0000  ...
                          pavements renewal      0.0000      0.0000  ...
                          pavements repair       0.0000      0.0000  ...
                          road marking           0.0000      0.0000  ...
                          tunnels                0.0000      0.0000  ...
           routine        bridges                0.0000      0.0000  ...
                          pavements           7264.2700   7264.2700  ...
                          tunnels                0.0000      0.0000  ...

                                                   2040        2041  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2042         2043  \
id_section operation_type item
0          periodic       bridges                0.0000       0.0000
                          pavements renewal      0.0000   89115.7000
                          pavements repair       0.0000       0.0000
                          road marking           0.0000       0.0000
                          tunnels                0.0000       0.0000
           routine        bridges                0.0000       0.0000
                          pavements           9080.3375    9080.3375
                          tunnels                0.0000       0.0000
1          periodic       bridges                0.0000       0.0000
                          pavements renewal      0.0000  712925.6000
                          pavements repair       0.0000       0.0000
                          road marking           0.0000       0.0000
                          tunnels                0.0000       0.0000
           routine        bridges                0.0000       0.0000
                          pavements          72642.7000   72642.7000
                          tunnels                0.0000       0.0000
2          periodic       bridges                0.0000       0.0000
                          pavements renewal      0.0000   71292.5600
                          pavements repair       0.0000       0.0000
                          road marking           0.0000       0.0000
                          tunnels                0.0000       0.0000
           routine        bridges                0.0000       0.0000
                          pavements           7264.2700    7264.2700
                          tunnels                0.0000       0.0000

                                                   2044        2045  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2046        2047  \
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

                                                   2048        2049
id_section operation_type item
0          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           9080.3375   9080.3375
                          tunnels                0.0000      0.0000
1          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements          72642.7000  72642.7000
                          tunnels                0.0000      0.0000
2          periodic       bridges                0.0000      0.0000
                          pavements renewal      0.0000      0.0000
                          pavements repair       0.0000      0.0000
                          road marking           0.0000      0.0000
                          tunnels                0.0000      0.0000
           routine        bridges                0.0000      0.0000
                          pavements           7264.2700   7264.2700
                          tunnels                0.0000      0.0000

[24 rows x 30 columns]

In [18]:
rcba.compute_residual_value()
rcba.RV_eco

Computing residual value...

,lifetime,replacement_cost_ratio,op_period,replace,rem_ratio,value,res_value
item,,,,,,,
land,inf,1.00,27,0,1.00,900000.0,900000.0
pavements asphalt,30.0,0.75,27,0,0.10,37800000.0,2835000.0
pavements concrete,30.0,0.75,27,0,0.10,0.0,0.0
bridges,100.0,1.00,27,0,0.73,4050000.0,2956500.0
tunnels,100.0,1.00,27,0,0.73,0.0,0.0
buildings,50.0,1.00,27,0,0.46,0.0,0.0
slope stabilisation,20.0,0.75,27,1,0.65,0.0,0.0
retaining walls,30.0,0.75,27,0,0.10,0.0,0.0
noise barriers,20.0,0.50,27,1,0.65,810000.0,263250.0
safety features,15.0,1.00,27,1,0.20,0.0,0.0

In [19]:
rcba._create_length_matrix()

Creating length matrix...

In [20]:
rcba._compute_travel_time_matrix()

Creating matrices of travel times...

In [21]:
rcba._compute_vtts()
rcba.NB["vtts"]

    Computing VTTS...

2020    0.000000e+00
2021    0.000000e+00
2022    0.000000e+00
2023    1.444438e+06
2024    1.458422e+06
2025    1.470233e+06
2026    1.485354e+06
2027    1.499453e+06
2028    1.514783e+06
2029    1.529016e+06
2030    1.543128e+06
2031    1.556663e+06
2032    1.569698e+06
2033    1.583739e+06
2034    1.596521e+06
2035    1.610689e+06
2036    1.626148e+06
2037    1.642902e+06
2038    1.658221e+06
2039    1.674009e+06
2040    1.689470e+06
2041    1.706277e+06
2042    1.723261e+06
2043    1.739903e+06
2044    1.757084e+06
2045    1.774438e+06
2046    1.791842e+06
2047    1.809424e+06
2048    1.825759e+06
2049    1.843028e+06
dtype: float64

In [22]:
rcba._compute_voc()

    Computing VOC...

In [23]:
rcba._compute_accidents()

    Computing accidents...

In [24]:
rcba._create_fuel_ratio_matrix()

Creating matrix of fuel ratios by vehicle...

In [25]:
rcba._compute_fuel_consumption()

    Computing fuel consumption...

In [26]:
rcba._compute_fuel_cost()

    Computing fuel cost...

In [27]:
rcba._compute_emissions()

    Computing emissions...

In [28]:
rcba._compute_greenhouse()

    Computing greenhouse gases...

In [29]:
rcba._compute_noise()

    Computing noise...

In [30]:
rcba.compute_economic_indicators()

Computing ENPV, ERR, BCR...

In [31]:
rcba.df_eco

                       2020        2021        2022        2023        2024  \
type    item
cost    capex   -14672000.0 -14672000.0 -14672000.0       -0.00       -0.00
        opex           -0.0        -0.0        -0.0   -87935.90   -87935.90
benefit res_val         0.0         0.0         0.0        0.00        0.00
        vtts            0.0         0.0         0.0  1444438.47  1458422.49
        voc             0.0         0.0         0.0   610608.50   616696.70
        acc             0.0         0.0         0.0   221804.96   223865.98
        fuel            0.0         0.0         0.0   159101.27   160688.78
        em              0.0         0.0         0.0   256850.05   259409.99
        ghg             0.0         0.0         0.0    32658.63    33852.48
        noise           0.0         0.0         0.0   388864.61   392491.38

                       2025        2026        2027        2028        2029  \
type    item
cost    capex         -0.00       -0.00       -0.00       -0.00       -0.00
        opex      -87935.90   -87935.90   -87935.90   -87935.90   -87935.90
benefit res_val        0.00        0.00        0.00        0.00        0.00
        vtts     1470232.58  1485354.36  1499453.25  1514782.51  1529016.17
        voc       622598.75   630565.97   638368.94   646418.29   654248.63
        acc       225690.04   227909.12   230055.21   232316.82   234482.24
        fuel      162232.92   164194.77   166118.17   168103.58   170038.23
        em        261949.15   265132.40   268297.23   271500.03   274678.51
        ghg        35054.44    36368.31    37695.11    39056.75    40428.34
        noise     395812.38   399725.03   403569.98   407500.72   411439.79

                 ...        2040        2041        2042        2043  \
type    item     ...
cost    capex    ...       -0.00       -0.00       -0.00       -0.00
        opex     ...   -87935.90   -87935.90   -87935.90   -87935.90
benefit res_val  ...        0.00        0.00        0.00        0.00
        vtts     ...  1689470.13  1706276.72  1723261.45  1739902.67
        voc      ...   736454.66   743802.11   751182.41   758584.61
        acc      ...   258636.04   261225.61   263842.87   266283.67
        fuel     ...   190991.40   192899.86   194820.81   196746.69
        em       ...   246679.39   249156.80   251646.26   254137.39
        ghg      ...    51616.03    52653.05    53703.70    54766.06
        noise    ...   453890.46   458480.29   463098.78   467433.45

                       2044        2045        2046        2047        2048  \
type    item
cost    capex         -0.00       -0.00       -0.00       -0.00       -0.00
        opex      -87935.90   -87935.90  -929375.72   -87935.90   -87935.90
benefit res_val        0.00        0.00        0.00        0.00        0.00
        vtts     1757084.06  1774438.07  1791841.73  1809423.51  1825759.36
        voc       766019.66   773482.09   780993.79   788538.34   796137.63
        acc       268935.95   271613.61   274311.88   277037.83   279605.57
        fuel      198685.04   200634.64   202595.33   204568.49   206559.06
        em        256640.57   259155.39   261673.97   264204.59   266748.94
        ghg        55842.21    56931.92    58035.22    59152.60    60285.54
        noise     472077.80   476750.79   481423.83   486125.51   490541.00

                       2049
type    item
cost    capex         -0.00
        opex      -87935.90
benefit res_val  6954750.00
        vtts     1843028.27
        voc       802284.97
        acc       282277.20
        fuel      208272.40
        em        269007.31
        ghg        61344.33
        noise     495266.38

[10 rows x 30 columns]

In [32]:
rcba.df_enpv

                       value
type    item
cost    capex   -41953269.84
        opex     -2077088.92
benefit res_val   1689630.93
        vtts     21125949.30
        voc       9083415.88
        acc       3237916.19
        fuel      2360650.55
        em        3599053.73
        ghg        588108.37
        noise     5681462.45